# 서버의 기본설정을 포트는 8000번, 주소는 localhost:8000/blog~를 기본으로 설정하고 인코디은 UTF-8로 설정
server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # @Controller과 같이 HTML파일을 리턴해야 할 경우 기본경로를 설정하고 .jsp라는 확장자를 붙여준다. (~/resources/static는 정적파일만 실행가능하기 때문에 jsp같은 동적 파일은 따로 설정)
  # src/main/webapp/WEB-INF/views 디렉토리를 직접 만들어 jsp 파일 폴더를 생성해준다. (jasper 라이브러리 설정하면 자동으로 웹서버 경로가 webapp으로 잡히기 때문에 그 이후만 설정)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # Mysql을 연결하고 3306번 포트에서 blog라는 DB를 사용하고 타임존은 서울로 설정한다.(연결을 위한 ID,PW 입렫)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: blog
    password: qwe123

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false